# Numpy Array

In [1]:
import numpy as np


In [2]:
#check all the functions in numpy
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

In [3]:
np.sqrt(10)

3.1622776601683795

In [4]:
print('Minimum  ',np.amin([25,30,57,18]))
print('Maximum  ',np.amax([25,30,57,18]))

Minimum   18
Maximum   57


In [5]:
#roundoff to next number
np.ceil(29.1)

30.0

In [6]:
np.ceil(np.sum(np.sqrt([5,10,15])))

10.0

**similarly there are many numpy functions , you can explore them for your knowlwdge purpose. But we use limited functions in our course let's explore them**

In [7]:
np.array([5,9,13])

array([ 5,  9, 13])

In [8]:
xyz= np.array([5,9,13])

In [9]:
type(xyz)

numpy.ndarray

In [10]:
#copy array into other
b = np.asarray(xyz)
print(b)

[ 5  9 13]


In [11]:
#dtype conversion
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

**data types**

In [12]:
my_mat =[[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/class of this object: ",type(mat))
print("here is the matrix\n---------\n",mat,"\n----------")
print("dimension of this matrix: ",mat.ndim)#ndim gives the dimension, 2 for matrix, 1 for vactors
print("size of this matrix: ",mat.size)#size gives the total number of element
print("shape of this matrix: ",mat.shape)#shape gives the number of element along each exes
print('data type of this matrix: ',mat.dtype)#dtype gives the datatype contained in the array

Type/class of this object:  <class 'numpy.ndarray'>
here is the matrix
---------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
dimension of this matrix:  2
size of this matrix:  9
shape of this matrix:  (3, 3)
data type of this matrix:  int32


# arange and linespace

In [13]:
#dont work with python range
list(range(2,10.5,.4))

TypeError: 'float' object cannot be interpreted as an integer

In [14]:
a = np.arange(2,10.5,.4)
a

array([ 2. ,  2.4,  2.8,  3.2,  3.6,  4. ,  4.4,  4.8,  5.2,  5.6,  6. ,
        6.4,  6.8,  7.2,  7.6,  8. ,  8.4,  8.8,  9.2,  9.6, 10. , 10.4])

In [15]:
#reverse order
a[::-1]

array([10.4, 10. ,  9.6,  9.2,  8.8,  8.4,  8. ,  7.6,  7.2,  6.8,  6.4,
        6. ,  5.6,  5.2,  4.8,  4.4,  4. ,  3.6,  3.2,  2.8,  2.4,  2. ])

In [16]:
print("Every fifth number from 50 in reverse order\n",np.arange(50,-1,-5))

Every fifth number from 50 in reverse order
 [50 45 40 35 30 25 20 15 10  5  0]


In [17]:
print("linearly spaced numbers between 10 and 40\n---------------------------------")
print(np.linspace(10,40,5))

linearly spaced numbers between 10 and 40
---------------------------------
[10.  17.5 25.  32.5 40. ]


In [18]:
#enclude end point and check space betweenthe points
#bydefault endpoint = true
#by default retstep = False
np.linspace(2.0,3.0, num=4, endpoint=False, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75]), 0.25)

In [19]:
print(np.linspace(4.567867,25.98656,39, retstep=True))

(array([ 4.567867  ,  5.13151682,  5.69516663,  6.25881645,  6.82246626,
        7.38611608,  7.94976589,  8.51341571,  9.07706553,  9.64071534,
       10.20436516, 10.76801497, 11.33166479, 11.89531461, 12.45896442,
       13.02261424, 13.58626405, 14.14991387, 14.71356368, 15.2772135 ,
       15.84086332, 16.40451313, 16.96816295, 17.53181276, 18.09546258,
       18.65911239, 19.22276221, 19.78641203, 20.35006184, 20.91371166,
       21.47736147, 22.04101129, 22.60466111, 23.16831092, 23.73196074,
       24.29561055, 24.85926037, 25.42291018, 25.98656   ]), 0.5636498157894737)


# Matrix Creation

In [20]:
print("vector of zeroes\n---------------------")
print(np.zeros(5))

vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [21]:
print("Matrix of zeroes\n---------------------")
print(np.zeros((5,6)))#notice tuples

Matrix of zeroes
---------------------
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [22]:
print("Matrix of ones\n---------------------")
print(np.ones((5,8)))#note matrix dimension specified by Tuples

Matrix of ones
---------------------
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [23]:
print("Matrix of ones\n---------------------")
print(5*np.ones((3,4)))

Matrix of ones
---------------------
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [24]:
#cunstruct diagonal matrix
x = np.arange(30).reshape(6,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


# Random Number Generation

In [25]:
np.random.seed(6) # each seed number will generate similar data
print("random number generation (from uniform distribution)")
print(np.random.randn(10,6))

random number generation (from uniform distribution)
[[-0.31178367  0.72900392  0.21782079 -0.8990918  -2.48678065  0.91325152]
 [ 1.12706373 -1.51409323  1.63929108 -0.4298936   2.63128056  0.60182225]
 [-0.33588161  1.23773784  0.11112817  0.12915125  0.07612761 -0.15512816]
 [ 0.63422534  0.810655    0.35480861  1.81259031 -1.3564758  -0.46363197]
 [ 0.82465384 -1.17643148  1.56448966  0.71270509 -0.1810066   0.53419953]
 [-0.58661296 -1.48185327  0.85724762  0.94309899  0.11444143 -0.02195668]
 [-2.12714455 -0.83440747 -0.46550831  0.23371059  1.38503523 -0.51962709]
 [-0.78015214  0.95560959 -0.12673638 -1.36861282  1.21848065 -0.85750144]
 [-0.56147088 -1.0335199   0.35877096  1.07368134 -0.37550472  0.39636757]
 [-0.47144628  2.33660781  1.50278553 -0.59545972  0.52834106  0.9398248 ]]


In [27]:
print(" number from Normal distribution with zero mean and started deviation 1 i.e. standard normal")
print(np.random.randn(10,3))

 number from Normal distribution with zero mean and started deviation 1 i.e. standard normal
[[ 0.52294535 -0.59187648 -0.47748711]
 [ 0.11252968  1.90474232  0.69415315]
 [-0.01958134  1.66284285  0.03060843]
 [-0.29749921 -0.96813764  0.16706673]
 [ 0.11660197 -0.68225732 -1.91402115]
 [-0.13990231  0.11492459 -0.39500464]
 [-0.95331626 -1.07282736 -0.48444561]
 [ 1.36293786  0.15268777 -1.6326206 ]
 [ 0.64330145 -0.44789505  2.33903423]
 [-0.31332286 -0.05961756  0.19416833]]


In [28]:
print("\nRandom integer matrix")
print(np.random.randint(1,30000,(6,7))) 


Random integer matrix
[[24641 15656  8972   599  3367 25489    10]
 [16534 12574 19711  7360 29664  7867  7193]
 [14019 13020 13077 18979   100 21484 21802]
 [ 8255 12325  7663 20160 19121 25216 16774]
 [ 3611 16808  5847  3810  3576 24615  1083]
 [17826 26054  8618  3293 19854  6174  5379]]


In [29]:
#one of the real time example of randint is
while True:
    otp1 = np.random.randint(1000, 10000, 1)
    print('Your OTP is - ', otp1)
    user_otp = int(input('Enter OTP '))
    if otp1 == user_otp:
        print('Login succesful')
        break
    else:
        print(' Generate new OTP')
        continue

Your OTP is -  [8506]
Enter OTP 


ValueError: invalid literal for int() with base 10: ''

**SORTING**

In [30]:
from numpy.random import randint as ri


In [31]:
M = ri(1,100,25).reshape(5,5)
print("\n5*5 Matrix of random integers\n", '-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M))
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0))


print('Minimum= ',M.min(), 'and Maximum = ', M.max())


5*5 Matrix of random integers
 -------------------------------------------------- 
 [[12 85 59 40 34]
 [22 68 53 32 69]
 [22  7  9 54 30]
 [24 60 97  4 53]
 [61 35  8 48 23]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[12 34 40 59 85]
 [22 32 53 68 69]
 [ 7  9 22 30 54]
 [ 4 24 53 60 97]
 [ 8 23 35 48 61]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[12  7  8  4 23]
 [22 35  9 32 30]
 [22 60 53 40 34]
 [24 68 59 48 53]
 [61 85 97 54 69]]
Minimum=  4 and Maximum =  97


**Numpy Condition**

In [32]:
#Below are employee salary.
emp_salary = ri(8,70,10)
emp_salary

array([ 8, 45, 54, 22, 69, 32, 37, 68, 48, 50])

In [33]:
#if you want to find actual salry whiuch are less than or greater than some salary use np.where
#np.where gives index details.
print(np.where(emp_salary<25))

(array([0, 3], dtype=int64),)


In [34]:
#fetch currosponding data
emp_salary[np.where(emp_salary<25)]

array([ 8, 22])

similarly you can check for any condition

In [35]:
#set minimum and maximum salary using a_min and a_max
np.clip(emp_salary, a_min=20, a_max=50)

array([20, 45, 50, 22, 50, 32, 37, 50, 48, 50])

# indexing and slicing

In [36]:
arr = np.arange(13,30)
print("Array:" , arr)

Array: [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [37]:
print("Element at 7th index is:", arr[7])

Element at 7th index is: 20


In [38]:
print("Element at 7th 4th and 9th index are:", arr[[7,4,9]])

Element at 7th 4th and 9th index are: [20 17 22]


In [39]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
print("\nDouble bracket indexing\n----------------------------")
print("Element in row index 1 and column index2:", mat[1][2])


Double bracket indexing
----------------------------
Element in row index 1 and column index2: 6


In [41]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
print("Entire row at index2:", mat[2])
print("\nEntire column at index: \n", mat[:,1:])

Entire row at index2: [7 8 9]

Entire column at index: 
 [[2 3]
 [5 6]
 [8 9]]


In [43]:
print("\nSubsetting sub-matrices\n------------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:2,1:2])


Subsetting sub-matrices
------------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[5]]


In [44]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
print("", mat[0:2,[1,2]])

 [[2 3]
 [5 6]]


**Update matrix**

In [46]:
print('Origina Matrix \n\n',mat)

Origina Matrix 

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
mat[0,1]=35
print(mat)

[[ 1 35  3]
 [ 4  5  6]
 [ 7  8  9]]


In [48]:
mat[1,0] = 100
print(mat)

[[  1  35   3]
 [100   5   6]
 [  7   8   9]]


**Subsseting**

In [52]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print('Matrix of random 2-digit number\n ------------------------------\n ', mat)

Matrix of random 2-digit number
 ------------------------------
  [[55 84 13 46 49]
 [76 52 32 91 60]
 [93 93 28 87 57]]


In [53]:
mat>50

array([[ True,  True, False, False, False],
       [ True,  True, False,  True,  True],
       [ True,  True, False,  True,  True]])

In [54]:
print("Elements greater than 50\n",mat[mat>50])

Elements greater than 50
 [55 84 76 52 91 60 93 93 87 57]


In [57]:
#you can also use np.where to return some data based on condition
marks = 50
np.where(marks > 68, 'Pass','fail')

array('fail', dtype='<U4')

In [58]:
#check non zeros
non_zero = ri(-10,50,100)

print(non_zero)
np.count_nonzero(non_zero)

[ -9  22  -5  26  34  25  10   6  10  44  39  -2   8  10   9  17  -5  48
  10  -5   5  27  -4  17   5  45  32  13   9  25  -8  24  47  42  27   7
  43  44  13  25  39  34  48  29  42   9   8  -3  16  47  17  10  37  31
  16  47   6  47  -6 -10   0  38  42  34  26   9  42  -1  33  16  33  26
  44  29  38   0   4  27  13  43  24  23   7  39   4  12  29  37  -4  10
  41  49  33  -9  38  47  21  36  16  28]


98

In [61]:
#ravel of flattarn (this concept is used in deep learning for nimage persenting)
array = np.random.randint(0, 20 , size = (3, 4))
print(array)
array.ravel()

[[16  1 10 15]
 [16  1  9  9]
 [ 2  5 11  8]]


array([16,  1, 10, 15, 16,  1,  9,  9,  2,  5, 11,  8])

In [62]:
#or flattern both are same
array.flatten()

array([16,  1, 10, 15, 16,  1,  9,  9,  2,  5, 11,  8])

# Universal function

In [63]:
mat1= np.array(ri(1,10,9)).reshape(3,3)
mat2= np.array(ri(1,10,9)).reshape(3,3)

print('\n1st matrix of random single digit numbers\n----------------------\n',mat1)
print('\n2nd matrix of random single digit numbers\n-----------------------\n',mat2)


1st matrix of random single digit numbers
----------------------
 [[5 7 8]
 [2 5 6]
 [2 4 1]]

2nd matrix of random single digit numbers
-----------------------
 [[2 3 9]
 [1 1 7]
 [3 6 6]]


In [64]:
print("\nAddition\n-------------------\n",         mat1+mat2)


Addition
-------------------
 [[ 7 10 17]
 [ 3  6 13]
 [ 5 10  7]]


In [65]:
print("\nMultiplication\n----------------\n",        mat1*mat2)


Multiplication
----------------
 [[10 21 72]
 [ 2  5 42]
 [ 6 24  6]]


**Broadcasting**

In [67]:
start = np.zeros((3,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [68]:
#creat a rank1 ndarray with 3 values
add_row = np.array([[1,0,2]])
print(add_row)

[[1 0 2]]


In [69]:
y = start + add_row #add to eaxch row of start using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [70]:
new_row = add_row.T
new_row

array([[1],
       [0],
       [2]])

In [72]:
test = new_row + start
print(test)

[[1. 1. 1.]
 [0. 0. 0.]
 [2. 2. 2.]]


**similarly you can apply other functions to matrix**